format_version: 10
pipelines:
  CleanCodeBuildTest:
    group: Example-Pipelines-Simple
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-6446443:
        git: https://github.com/Jitendra-Yashwantrao/CleanCodeGo.git
        shallow_clone: false
        auto_update: true
        branch: master
    stages:
    - build:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          Install_vet:
            timeout: 0
            tasks:
            - exec:
                arguments:
                - install-dep
                command: ./sam.sh
                run_if: passed
    parameters:
      Param1: Test
      Param2: Test2
